language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode8

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
    packages:
      - qt5-default
      - qttools5-dev-tools
      - qtmultimedia5-dev
      - libqt5multimedia5-plugins
      - libasound2-dev
  homebrew:
    packages:
      - qt5

git:
  depth: 3

branches:
  only:
    - master
    # for testing on local clone:
    - travis_osx

before_install:
  # osx: linking qt5 into PATH etc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link --force qt5; fi

script:
  - cd BambooTracker
  - qmake
  - make
