language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode6.4

git:
  depth: 3

branches:
  only:
    - master
    # for testing on local clone:
    - travis_osx

# to differenciate between the package acquisition methods
# of Linux and macOS, we run bash script that does the logic
# and platform-specific package installation
before_install:
  - ./.travis/beforeInstall.sh

script:
  - cd BambooTracker
  - qmake
  - make
