language: cpp

jobs:
  include:
  - name: Windows (7 and later)
    os: windows
    env:
    - TARGET_OS=windows
    - MAKE=mingw32-make
    - QMAKE=qmake.exe
    - MINGWVER=7.3.0
    - QTDIR=$HOME/Qt/win7
    - QTVER=5.14.1
    - QTTCH=win32_mingw73
    before_install:
    # We *need* to manually install 32-Bit MinGW
    - bash "$TRAVIS_BUILD_DIR"/ci/fetch_mingw.sh "$MINGWVER"
    - MINGWPATH="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw32"
    # Neither Travis CI nor Chocolatey have a Qt package, so we fetch it from upstream.
    - bash "$TRAVIS_BUILD_DIR"/ci/fetch_qt.sh "$QTDIR" "$QTVER" "$QTTCH"
      qtbase qtmultimedia qttools
    - QTPATH="$(echo "$QTDIR"/"$QTVER"/*)"
    - export PATH="$MINGWPATH"/bin:"$QTPATH"/bin:"$PATH"
    before_deploy:
    - bash "$TRAVIS_BUILD_DIR"/ci/package_windows.sh
  - name: Windows (XP)
    os: windows
    env:
    - TARGET_OS=windows-xp
    - MAKE=mingw32-make
    - QMAKE=qmake.exe
    - MINGWVER=4.9.3
    - QTDIR=$HOME/Qt/winXP
    - QTVER=5.5
    - QTTCH=win32_mingw492
    before_install:
    # We *need* to manually install 32-Bit MinGW
    - bash "$TRAVIS_BUILD_DIR"/ci/fetch_mingw.sh "$MINGWVER"
    - MINGWPATH="/c/tools/mingw32"
    # Neither Travis CI nor Chocolatey have a Qt package, so we fetch it from upstream.
    - bash "$TRAVIS_BUILD_DIR"/ci/fetch_qt.sh "$QTDIR" "$QTVER" "$QTTCH"
      essentials addons
    - QTPATH="$(echo "$QTDIR"/"$QTVER"/*)"
    - export PATH="$MINGWPATH"/bin:"$QTPATH"/bin:"$PATH"
    before_deploy:
    - bash "$TRAVIS_BUILD_DIR"/ci/package_windows.sh

  - name: macOS (Xcode 11.3)
    os: osx
    osx_image: xcode11.3
    env:
    - TARGET_OS=macos
    - MAKE=make
    - QMAKE="qmake DEFINES+=__UNIX_JACK__"
    before_install:
    # force linking of qt into PATH
    - brew link --force qt
    # Manually append JACK includes to qmake,
    # it doesn't seem to pick them up on its own (forcing linking didn't help)
    - JACKLIB=$(find /usr/local/Cellar/jack/ -type d -name lib)
    - JACKINC=$(find /usr/local/Cellar/jack/ -type d -name include)
    - export QMAKE="$QMAKE LIBS+=-L$JACKLIB INCLUDEPATH+=$JACKINC"
    before_deploy:
    - bash "$TRAVIS_BUILD_DIR"/ci/package_macos.sh
  - name: macOS (Xcode 9.3)
    os: osx
    osx_image: xcode9.3
    env:
    - TARGET_OS=macos-legacy
    - MAKE=make
    - QMAKE="qmake DEFINES+=__UNIX_JACK__"
    before_install:
    # Force linking of Qt into PATH
    - brew link --force qt
    # Manually append JACK includes to qmake,
    # it doesn't seem to pick them up on its own (forcing linking didn't help)
    - JACKLIB=$(find /usr/local/Cellar/jack/ -type d -name lib)
    - JACKINC=$(find /usr/local/Cellar/jack/ -type d -name include)
    - export QMAKE="$QMAKE LIBS+=-L$JACKLIB INCLUDEPATH+=$JACKINC"
    before_deploy:
    - bash "$TRAVIS_BUILD_DIR"/ci/package_macos.sh

  - name: Linux (Ubuntu 16.04)
    os: linux
    dist: xenial
    env:
    - TARGET_OS=linux
    - MAKE=make
    - QMAKE="qmake DEFINES+=__LINUX_PULSE__ DEFINES+=__UNIX_JACK__"
    # no deployment phase, manual build is preferred on Linux
    # TODO consider Appimage?

cache:
  directories:
  - $HOME/Qt

addons:
  homebrew:
    packages:
    - jack
    - qt
    - p7zip
    update: true
  apt:
    sources:
    - sourceline: ppa:ubuntu-sdk-team/ppa
    packages:
    - qt5-default
    - qttools5-dev-tools
    - qtmultimedia5-dev
    - libqt5multimedia5-plugins
    - libasound2-dev
    - libpulse-dev
    - libjack-dev

git:
  depth: 3

branches:
  only:
  - master
  - "/^v[0-9\\.]+$/"

script:
- cd BambooTracker
- "$QMAKE CONFIG+=release CONFIG-=debug"
- "$MAKE -j2"

deploy:
  provider: releases
  api_key:
    secure: "NXKmuVsiua4LP3t3vV0sk4rozJMIyrbF7fJmf3XygKfoSqaAI5fuSIYlANwH30Q7u2F/+qyROi2jJVl9AvFmGpYar2yd4fVjM/4e0ax7lswqMzCIkFEZ6IkQyAyC7mZRfbxkH7Wd1ECNFtInvJcL+nB9Odxf3JovpNzBHutiJkoPCD4cv3qRuUOASyHxZBFxk+MSkX7jZunKFBfi2icYVX3PcIZZQMWY4a1gPYBIS7GwaK0t15zbFh1vZkuHMch8hJr5DsD4PR8y9XyaFxDYXRDNeDvYYUYJE5NxelBYBFf+AOSKKjHQyRze418O5yFsDjW7iH2SJw3VUx6UfbH/ohwoMQxBhYmpO4i5/Q1yyeA+70iWsOXALhEHYzRK6yOW2toNSsBKXCGFgwD+pmhZLqktXPS1368pFKMcIZHGJQ5ZmOfZXT81MH079ntwo2MXUZwWIDCgKK8nLiaWAEQBBzkIvGvokjaPzz+jk+ID02u8Y7bSO2j6OUC+UnumHLZrPnermoRzvBEIP/fCJ3d/rX4VBSs9iZWgsNwuWuQGeb+EECZUbbHtxEtM4C1Io1bh0f4/1WJzrjkYBWfsc/W4tUggX3I3yOdQ69qGe7A1XjqXWh5eHtKXvjR8PtpkwTJMnXWNe0VuMNJGu3cvL66PMXVfi3Y5UaP5I1uWiSh7Oj8="
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/BambooTracker-$TRAVIS_TAG-$TARGET_OS.zip"
  on:
    repo: OPNA2608/BambooTracker
    tags: true
    condition: $TRAVIS_OS_NAME != linux
