name: Windows (Modern)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TARGET:   windows
  MINGW_VERSION:  7.3.0
  MINGW_PATH:     /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw32
  QT_BASE_PATH:   Qt
  QT_VERSION:     5.14.1
  QT_TOOLCHAIN:   win32_mingw73
  QT_MODULES:     qtbase qtmultimedia qttools

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name:  Checking out repo.
      uses:  actions/checkout@v2

    - name:  Fetching cache.
      id:    cache
      uses:  actions/cache@v1
      with:
        path: ${{ github.workspace }}/${{ env.QT_BASE_PATH }}
        key:  ${{ runner.os }}_Qt${{ env.QT_VERSION }}_${{ env.QT_TOOLCHAIN }}

    - name:  Installing requested Qt version.
      shell: bash
      run:   |
        ./ci/fetch_qt.sh /d/a/BambooTracker/BambooTracker/${{ env.QT_BASE_PATH }} ${{ env.QT_VERSION }} ${{ env.QT_TOOLCHAIN }} ${{ env.QT_MODULES }}
        echo "::add-path::$(echo /d/a/BambooTracker/BambooTracker/${{ env.QT_BASE_PATH }}/${{ env.QT_VERSION }}/*/bin)"

    # Adding MinGW to the PATH via ::add-path here seems pointless,
    # the existing MinGW takes priority and causes the build to fail.
    # Instead, manually prepend the MinGW path to PATH before invocations.
    - name:  Installing requested MinGW version.
      shell: bash
      run:   ./ci/fetch_mingw.sh "${{ env.MINGW_VERSION }}"

    - name:  Configuring.
      shell: bash
      run:   |
        export PATH="${{ env.MINGW_PATH }}/bin:$PATH"
        cd BambooTracker
        qmake.exe BambooTracker.pro CONFIG+=debug CONFIG+=console CONFIG+=nostrip

    - name:  Building.
      shell: bash
      run:   |
        export PATH="${{ env.MINGW_PATH }}/bin:$PATH"
        cd BambooTracker
        mingw32-make -j2

    - name:  Packaging.
      shell: bash
      run:   |
        export PATH="${{ env.MINGW_PATH }}/bin:$PATH"
        ls -ahl ci
        mkdir packaging
        cd packaging
        ../ci/package_windows.sh


    - name:  Uploading artifact
      uses:  actions/upload-artifact@v1
      with:
        name: BambooTracker-debug-${{ env.BUILD_TARGET }}-master
        path: packaging

